export const positionTop = 'top'
export const positionRight = 'right'
export const positionBottom = 'bottom'
export const positionLeft = 'left'

export const groupModeSingle = 'single'
export const groupModeSeries = 'series'
export const groupModePrimary = 'primary'
export const groupModeSecondary = 'secondary'

export const alignAuto = 'auto'
export const alignRight = 'right'
export const alignTopRight = 'topRight'
export const alignBottomRight = 'bottomRight'
export const alignLeft = 'left'
export const alignTopLeft = 'topLeft'
export const alignBottomLeft = 'bottomLeft'
export const alignTop = 'top'
export const alignBottom = 'bottom'
