name: react-charts publish
on:
  push:
    branches:
      - 'next'
  pull_request:

jobs:
  # test:
  #   name: 'node ${{ matrix.node }} ${{ matrix.os }} '
  #   runs-on: '${{ matrix.os }}'
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #       node: [12, 14, 16]
  #   steps:
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node }}
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #     - run: npm i -g yarn
  #     - run: yarn --frozen-lockfile
  #     - run: yarn test:ci

  publish-module:
    name: 'Publish Module to NPM'
    # needs: test
    if: github.ref == 'refs/heads/next' #publish only when merged in master, not on PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm i -g yarn
      - run: yarn --frozen-lockfile
      - run: npx semantic-release@17
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
